# Generated by Django 4.2.30 on 2026-08-10 13:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import interview.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], default='M', max_length=1, verbose_name='性别')),
                ('political_status', models.CharField(max_length=20, verbose_name='政治面貌')),
                ('school', models.CharField(choices=[('HG', '化工学院'), ('HF', '化学与分子工程学院'), ('SG', '生物工程学院'), ('YX', '药学院'), ('CL', '材料科学与工程学院'), ('XX', '信息科学与工程学院'), ('JX', '机械与动力工程学院'), ('ZH', '资源与环境工程学院'), ('SY', '数学学院'), ('WL', '物理学院'), ('SX', '商学院'), ('SH', '社会与公共管理学院'), ('YS', '艺术设计与传媒学院'), ('WG', '外国语学院'), ('FX', '法学院'), ('TY', '体育科学与工程学院'), ('GZ', '国际卓越工程师学院'), ('UN', '请选择学院')], default='UN', max_length=2, verbose_name='学院')),
                ('homeroom', models.CharField(max_length=20, verbose_name='班级')),
                ('telephone', models.CharField(help_text='请输入11位中国手机号', max_length=11, validators=[django.core.validators.RegexValidator(message='请输入有效的中国手机号（11位数字）', regex='^1[3-9]\\d{9}$')], verbose_name='手机号')),
                ('student_number', models.CharField(help_text='请输入8位学号', max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='请输入有效的学号（8位数字）', regex='^2[0-6]\\d{6}$')], verbose_name='学号')),
                ('qq_id', models.CharField(max_length=15, verbose_name='QQ号')),
                ('wx_id', models.CharField(max_length=50, verbose_name='微信号')),
                ('email', models.EmailField(max_length=254, verbose_name='电子邮箱')),
                ('character', models.TextField(help_text='兴趣爱好及特长', validators=[interview.validators.WordCountValidator(field_name='兴趣爱好及特长', max_words=500)], verbose_name='兴趣爱好及特长')),
                ('introduction', models.TextField(help_text='自我介绍及评价（150字以内）', validators=[interview.validators.WordCountValidator(field_name='自我介绍及评价', max_words=150)], verbose_name='自我介绍及评价')),
                ('experience', models.TextField(blank=True, help_text='学生工作经历', validators=[interview.validators.WordCountValidator(field_name='学生工作经历', max_words=500)], verbose_name='学生工作经历')),
                ('honor', models.TextField(blank=True, help_text='所获荣誉', validators=[interview.validators.WordCountValidator(field_name='所获荣誉', max_words=500)], verbose_name='所获荣誉')),
                ('status', models.CharField(choices=[('INCOMPLETE', '未完善'), ('REGISTERED', '已报名'), ('WAITING', '候场中'), ('INQUEUE', '队列中'), ('INTERVIEWING', '面试中'), ('COMPLETED', '已完成')], default='INCOMPLETE', max_length=20, verbose_name='面试状态')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], default='M', max_length=1, verbose_name='性别')),
                ('political_status', models.CharField(max_length=20, verbose_name='政治面貌')),
                ('department', models.CharField(choices=[('BGS', '办公'), ('XCB', '信传'), ('QYB', '权益'), ('XSB', '学实'), ('WYB', '文艺'), ('TYB', '体育'), ('UNK', '未知')], default='UNK', max_length=3, verbose_name='部门')),
                ('homeroom', models.CharField(max_length=20, verbose_name='组别')),
                ('telephone', models.CharField(help_text='请输入11位中国手机号', max_length=11, validators=[django.core.validators.RegexValidator(message='请输入有效的中国手机号（11位数字）', regex='^1[3-9]\\d{9}$')], verbose_name='手机号')),
                ('student_number', models.CharField(help_text='请输入8位学号', max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='请输入有效的学号（8位数字）', regex='^2[0-6]\\d{6}$')], verbose_name='学号')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['department', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('BGS', '办公'), ('XCB', '信传'), ('QYB', '权益'), ('XSB', '学实'), ('WYB', '文艺'), ('TYB', '体育'), ('UNK', '未知')], max_length=3, verbose_name='志愿部门')),
                ('priority', models.PositiveSmallIntegerField(help_text='1=第一志愿，2=第二志愿，3=第三志愿', verbose_name='志愿优先级')),
                ('queue_start_time', models.DateTimeField(blank=True, help_text='志愿进入队列的时间', null=True, verbose_name='开始排队时间')),
                ('status', models.CharField(choices=[('FILLED', '已填报'), ('WAITING', '排队中'), ('INQUEUE', '队列中'), ('INTERVIEWING', '面试中'), ('COMPLETED', '已完成'), ('REJECTED', '已淘汰'), ('ACCEPTED', '已录取')], default='FILLED', max_length=20, verbose_name='志愿状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='interview.candidate', verbose_name='面试者')),
            ],
            options={
                'verbose_name': '志愿信息',
                'verbose_name_plural': '志愿信息管理',
                'ordering': ['candidate', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', '超级管理员'), ('admin', '主管理员'), ('subadmin', '部门管理员'), ('interviewer', '面试官'), ('candidate', '面试者'), ('guest', '访客')], default='candidate', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户档案',
                'verbose_name_plural': '用户档案管理',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='InterviewGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departments', models.CharField(choices=[('BGS', '办公'), ('XCB', '信传'), ('QYB', '权益'), ('XSB', '学实'), ('WYB', '文艺'), ('TYB', '体育'), ('UNK', '未知')], default='UNK', max_length=3, verbose_name='部门')),
                ('group_id', models.CharField(blank=True, max_length=50, verbose_name='组名')),
                ('interview_date', models.DateTimeField(auto_now_add=True, verbose_name='面试时间')),
                ('status', models.CharField(choices=[('PENDING', '待开始'), ('ONGOING', '进行中'), ('PAUSE', '暂停中'), ('ENDED', '已结束'), ('CANCELLED', '已取消')], default='PENDING', max_length=10, verbose_name='面试状态')),
                ('basic_question1', models.TextField(blank=True, validators=[interview.validators.WordCountValidator(field_name='基本题1', max_words=500)], verbose_name='基本题1')),
                ('basic_question2', models.TextField(blank=True, validators=[interview.validators.WordCountValidator(field_name='基本题2', max_words=500)], verbose_name='基本题2')),
                ('rush_question', models.TextField(blank=True, validators=[interview.validators.WordCountValidator(field_name='抢答题1', max_words=500)], verbose_name='抢答题1')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='面试开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='面试结束时间')),
                ('interviewers', models.ManyToManyField(related_name='interview_groups', to='interview.interviewer', verbose_name='面试官')),
            ],
            options={
                'verbose_name': '面试组',
                'verbose_name_plural': '面试组管理',
                'ordering': ['-interview_date'],
            },
        ),
        migrations.CreateModel(
            name='InterviewerScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_intro', models.TextField(blank=True, help_text='面试官记录的面试者现场自我介绍', validators=[interview.validators.WordCountValidator(field_name='自我介绍', max_words=300)], verbose_name='自我介绍')),
                ('comment', models.TextField(blank=True, help_text='面试官对面试者的综合评价', validators=[interview.validators.WordCountValidator(field_name='评语', max_words=300)], verbose_name='评语')),
                ('score', models.DecimalField(decimal_places=2, default=0.0, help_text='请输入0-10，保留两位小数', max_digits=4, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(10.0)], verbose_name='评分')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='interview.candidate', verbose_name='面试者')),
                ('interview_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='interview.interviewgroup', verbose_name='面试场次')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='interview.interviewer', verbose_name='面试官')),
            ],
            options={
                'verbose_name': '面试官评分',
                'verbose_name_plural': '面试官评分',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='组名')),
                ('department', models.CharField(choices=[('BGS', '办公'), ('XCB', '信传'), ('QYB', '权益'), ('XSB', '学实'), ('WYB', '文艺'), ('TYB', '体育'), ('UNK', '未知')], max_length=3, verbose_name='部门')),
                ('status', models.CharField(choices=[('ONUSE', '启用中'), ('WORKING', '工作中'), ('ENDED', '已销毁')], default='ONUSE', max_length=8, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('chief', models.ForeignKey(blank=True, help_text='该组的主面试官', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chief_of_group', to='interview.interviewer', verbose_name='主面试官')),
                ('members', models.ManyToManyField(related_name='groups', to='interview.interviewer', verbose_name='组成员')),
            ],
            options={
                'verbose_name': '面试官组',
                'verbose_name_plural': '面试官组管理',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CandidateInGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(help_text='面试者在组内的顺序（1-6）', verbose_name='序号')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='interview.candidate', verbose_name='面试者')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='interview.interviewgroup', verbose_name='所属面试组')),
            ],
            options={
                'verbose_name': '组内面试者',
                'verbose_name_plural': '组内面试者',
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='volunteer',
            constraint=models.CheckConstraint(check=models.Q(('priority__gte', 1), ('priority__lte', 3)), name='volunteer_priority_range_1_3'),
        ),
        migrations.AlterUniqueTogether(
            name='volunteer',
            unique_together={('candidate', 'priority'), ('candidate', 'department')},
        ),
        migrations.AlterUniqueTogether(
            name='interviewerscore',
            unique_together={('candidate', 'interviewer')},
        ),
        migrations.AddConstraint(
            model_name='candidateingroup',
            constraint=models.CheckConstraint(check=models.Q(('order__gte', 1), ('order__lte', 6)), name='candidate_order_range_1_6'),
        ),
        migrations.AlterUniqueTogether(
            name='candidateingroup',
            unique_together={('group', 'order')},
        ),
    ]
