# Generated by Django 4.2.30 on 2026-08-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_candidate_adjustable_candidate_racetrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='avatar',
            field=models.ImageField(blank=True, help_text='请上传个人证件照，支持jpg/png格式', null=True, upload_to='avatars/', verbose_name='证件照'),
        ),
    ]
