# Generated by Django 4.2.30 on 2026-08-14 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_alter_candidate_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='avatar_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/thumbnails/', verbose_name='证件照缩略图'),
        ),
    ]
