# Generated by Django 4.2.30 on 2026-08-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0007_align_legacy_profile_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateingroup',
            name='call_status',
            field=models.CharField(choices=[('WAITING', '等待叫号'), ('CALLED', '已叫号'), ('INTERVIEWING', '正在面试'), ('FINISHED', '面试完成')], default='WAITING', max_length=15, verbose_name='叫号状态'),
        ),
        migrations.AddField(
            model_name='candidateingroup',
            name='called_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='叫号时间'),
        ),
        migrations.AddField(
            model_name='candidateingroup',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='面试完成时间'),
        ),
        migrations.AddField(
            model_name='interviewgroup',
            name='classroom',
            field=models.CharField(blank=True, default='', help_text='留空时叫号看板显示"待安排"', max_length=20, verbose_name='面试教室'),
        ),
    ]
