# Generated by Django 4.2.30 on 2026-08-22 12:27

import django.core.validators
from django.db import migrations, models


def convert_scores_to_percent(apps, schema_editor):
    """将旧的0-10分转换为0-100分（乘以10）"""
    InterviewerScore = apps.get_model('interview', 'InterviewerScore')
    for score_obj in InterviewerScore.objects.all():
        old_score = float(score_obj.score)
        if old_score > 0:
            # 转换为百分制
            new_score = old_score * 10
            score_obj.score = new_score
            score_obj.save(update_fields=['score'])


def reverse_convert_scores(apps, schema_editor):
    """将百分制分数还原为0-10分（除以10）"""
    InterviewerScore = apps.get_model('interview', 'InterviewerScore')
    for score_obj in InterviewerScore.objects.all():
        old_score = float(score_obj.score)
        if old_score > 0:
            new_score = old_score / 10
            score_obj.score = new_score
            score_obj.save(update_fields=['score'])


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0008_candidateingroup_call_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewerscore',
            name='dimension_scores',
            field=models.JSONField(blank=True, default=dict, help_text='存储各评分维度的具体得分，格式：{dimension_code: score}', verbose_name='各维度得分'),
        ),
        migrations.AlterField(
            model_name='interviewerscore',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='百分制评分，由各维度得分自动计算', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='总分'),
        ),
        migrations.RunPython(
            convert_scores_to_percent,
            reverse_convert_scores
        ),
    ]
