# Generated by Django 4.2.30 on 2026-08-23 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0009_add_dimension_scores_to_interviewerscore'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interviewerscore',
            unique_together={('candidate', 'interviewer', 'interview_group')},
        ),
    ]
