# Generated by Django 4.2.30 on 2026-08-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='adjustable',
            field=models.CharField(choices=[('Y', '是'), ('N', '否'), ('O', '或')], default='O', max_length=1, verbose_name='服从调剂'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='racetrack',
            field=models.CharField(choices=[('POL', '破浪赛道'), ('ZHU', '逐浪赛道'), ('UNK', '暂未选择')], default='UNK', max_length=3, verbose_name='赛道'),
        ),
    ]
