# Generated by Django 4.2.30 on 2026-08-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_candidate_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='avatar',
            field=models.ImageField(blank=True, help_text='请上传个人证件照，支持jpg/png格式', null=True, upload_to='avatar/', verbose_name='证件照'),
        ),
    ]
